### ISSUE TITLE
Dont know it

### ISSUE THREAD

**Issue by CrafterMinecrafter** [RicoBrase/ChatCalculator#4]
Where minecraft source?

**Comment by RicoBrase** [comment]
What do you mean?

**Comment by CrafterMinecrafter** [comment]
> What do you mean?

I have a problem in Intelij Idea, there are no minecraft libraries

**Comment by RicoBrase** [comment]
Ah, okay.

You should setup your workspace following one of the many tutorials out there on the internet (in the search engine of your choice: "minecraft forge 1.12 modding tutorial").
I can't include the minecraft sources and all the libraries in this repository (e.g. because of licensing problems).

If I find the time, I may write a how-to on how I setup my workspace for this mod in the following weeks, but I'm currently busy working on other projects.

(Closing for now, since this is - technically - not a problem with this mod.)
